version: '2.1'
services:
  hug-api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672" # For management interface
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  selenium-automation:
    build:
      context: ./selenium-automation/
      dockerfile: Dockerfile
    env_file:
      - ./selenium-automation/.env
    depends_on:
      - hug-api
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
